### ISSUE TITLE
feature roadmap

### ISSUE THREAD

**Issue by hsinhoyeh** [FootprintAI/restcol#19]
- [x] add doc api https://github.com/FootprintAI/restcol/pull/21
- [x] add integration test https://github.com/FootprintAI/restcol/pull/22
- [x] query docs https://github.com/FootprintAI/restcol/pull/30
